name: Testes unitários do map.js

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Utilize a versão que preferir

     # 3. Instalar dependências na pasta correta
      - name: Install dependencies
        run: |
          cd TestesMapa/obrasgov
          npm install

      # 4. Executar os testes
      - name: Run tests
        run: npx jest --coverage
        working-directory: TestesMapa/js
