name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    paths: 
      - 'obrasgov/**'
      - 'css/**'
      - 'js/**'
      - 'index.html'
  repository_dispatch:
    types: [deploy]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create build directory
      run: |
        mkdir -p dist
        cp -r css dist/
        cp -r js dist/
        cp -r obrasgov dist/
        cp index.html dist/
        
        echo "{\"buildTime\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"commit\":\"${{ github.sha }}\"}" > dist/build-info.json

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4