name: Atualizar Gráficos Semanalmente

on:
  schedule:
    - cron: '0 8 * * 1'  
  workflow_dispatch:      

jobs:
  gerar-graficos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r graficos/requirements.txt

      - name: Gerar gráficos
        run: |
          python graficos/moduloDeGraficos.py

      - name: Commit e push dos gráficos atualizados
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add graficos/static/graficos/*.png
          git commit -m "Atualização automática dos gráficos [skip ci]" || echo "Nada para commitar"
          git push